### ISSUE TITLE
Updates with nested create + array, results in Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by TrevHeath** [morintd/prismock#1016]
If you have a mutation with a nested create and you pass an array, it results in a `Cannot read properties of undefined (reading 'map')`. 

```
await context.prisma.post.update({
  where: {
    id
  },
  data: {
      files: {
          create: array.map((item) => ({
          url: item.url
        }))
      }
    }
  })
```

I quickly looked at the code and it appears to be an issue here `src/lib/operations/update.ts`:

```
else {
              if (Array.isArray(fieldData.create)) {
                fieldData.createMany
                  .map(formatCreatedItem)
                  .forEach((createSingle: Item) => delegate.create({ data: createSingle }));
              }
```

**Comment by morintd** [comment]
Hello @TrevHeath , I'm surprised this is working with Prisma. In this case, shouldn't your `create` under `files` be a `createMany` instead?

Let me know if that fixes the issue, I'll dive into the code of `prismock`otherwise.

**Comment by TrevHeath** [comment]
Hey @morintd, thanks for the reply.  Both are valid operations in Prisma and are used for different use cases, `create` allows for nested relations while `createMany` allows you to skip duplicates.  

[create vs createMany](https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries#create-a-single-record-and-multiple-related-records)
