### ISSUE TITLE
Interactive transactions

### ISSUE THREAD

**Issue by Toinouze** [morintd/prismock#240]
Hi, thanks for the awesome tool !

I use interactive transactions, which are not supported by prismock atm.
I currently use a dirty workaround :

```typescript
Object.assign(await generatePrismock(), {
   $transaction(fn: any) {
      return fn(undefined);
   },
});
```
      
 Do you think you could add this natively in prismock ? It would be great.
 Thanks !

**Comment by morintd** [comment]
Added in [v1.8.0](https://github.com/morintd/prismock/releases/tag/v1.8.0)
