### ISSUE TITLE
Helper methods to set/reset data

### ISSUE THREAD

**Issue by Toinouze** [morintd/prismock#241]
Would be nice to have synchronous typesafe simple methods for setup/teardown operations in tests : 
```typescript
const client = await generatePrismock();
client.resetDataForModel("myModel");
client.setDataForModel("myModel", []);
client.resetAllData();
```
Current `getData` and `setData` are not very usable for this purpose.

**Comment by morintd** [comment]
I don't plan to add this at the moment.

The `getData` / `setData` utils, as well as the `create` operation should be enough. I prefer to avoid adding more complexity.
