### ISSUE TITLE
Use with custom Prisma output dir

### ISSUE THREAD

**Issue by nicaura** [morintd/prismock#298]
When using custom `output` param from `prisma.schema`
```sql
generator client {
  provider        = "prisma-client-js"
  output          = "./src/generated/prisma/client"
  previewFeatures = ["postgresqlExtensions"]
}
```
... it looks like the prismock library looks for a client under `@prisma/client` however it should look under `src/generated/prisma/client`. 

Is there a way to force that ?

**Comment by morintd** [comment]
Hello, thanks for your submission, I’ll have a look in the following days

**Comment by morintd** [comment]
Hello @nicaura , from what I understand, you want to use `prismock` using the types from a `PrismaClient` generated inside a custom directory (from the `output` configuration)?

After reading https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client#using-a-custom-output-path, I guess the only solution is to allow a custom client to be passed when using `prismock`.

Can you confirm if I understood your requirements correctly, and if that's the case, if https://github.com/morintd/prismock/pull/303/files might be what you are looking for?

**Comment by nicaura** [comment]
Thanks @morintd, that's exactly it and it does the job !
