### ISSUE TITLE
[Enhancement] A synchronous `generatePrismock` function

### ISSUE THREAD

**Issue by Teagan42** [morintd/prismock#329]
Currently, the `generatePrismock` function is asynchronous because it has to process the Datamodel Meta Format (DMMF). In many instances, we have access to the resulting Models. By augmenting the `Options` interface to accept an array of Models, the process is now synchronous.

The models are available via the generated `PrismaClient`:
```
import { PrismaClient, Prisma } from "./__generated__/client";

const models = Prisma.dmmf.datamodel.models;
```

Changes to the code:

```
type Options = {
  schemaPath?: string;
  models?: DMMF.Model[]
};
```

```
export function generatePrismock<T = PrismaClient>(options: Options = {}): PrismockClient<T> | PromisePrismockClient<T>> {
    const schema = await generateDMMF(options.schemaPath);
    const { models } = options.models ?? (await generateDMMF(options.schemaPath)).dataModel;
```

When I get a chance I will submit a PR just busy

**Comment by morintd** [comment]
Hello, that's a great suggestion I'm 100% in favor of supporting!

I answered directly on https://github.com/morintd/prismock/pull/330.
