### ISSUE TITLE
Feature Request - `cuid` support

### ISSUE THREAD

**Issue by samepant** [morintd/prismock#509]
Prismock is awesome, thanks for maintaining it 💎

`cuid` support would be amazing (doesn't even have to be real cuid, a close, faster approximation would work great)

**Comment by morintd** [comment]
Hello @samepant , thanks a lot 🙏

I'm surprised I didn't add it yet, I'll have a look as soon as I'm done with orderBy!

**Comment by samepant** [comment]
incredible, thx for the speedy feature add
🔥 🔥 🔥 🔥
