### ISSUE TITLE
Way to reset Prismock database after each test

### ISSUE THREAD

**Issue by samepant** [morintd/prismock#519]
I think this is already supported, but i couldn't find a way to do it that works. An example of how to reset the Prisma db before each test / after each test would be amazing.

thanks again for this incredibly useful package 🙏

**Comment by morintd** [comment]
Hello @samepant , there isn't really a feature to reset the database included. For now, you have to re-create an instance of your db (or the object that uses it) to get a completely fresh one.

I'll have a look on how to include that, but supporting other features is definitely higher priority.

**Comment by morintd** [comment]
It was quite quick actually, let me know what you think, you can see a reset function in the [README](https://github.com/morintd/prismock/pull/524).

Merged [here](https://github.com/morintd/prismock/pull/524).
