### ISSUE TITLE
Support `prisma.$extends`

### ISSUE THREAD

**Issue by Foxious** [morintd/prismock#532]
We've started using [prisma accelerate](https://www.prisma.io/docs/data-platform/accelerate/getting-started), which required us to use `.$extends` on existing client. Prismock does not support this method, so if I try to call any of our existing prisma methods, I get the following error:

```
TypeError: prisma.$extends is not a function
```

I really want to be able to use prismock in our environment, but without this we can't put any existing code under test

**Comment by morintd** [comment]
Hello @Foxious , thanks for the support. I added a basic $extends function which should allow you to use Prismock (1.18.0).

The current $extends doesn't implement anything, just respect the Prisma's API. I believe that's enough for your use-case, feel free to let me know if you have any issue.
