### ISSUE TITLE
Not resetting data after each test

### ISSUE THREAD

**Issue by guilherme-n** [morintd/prismock#549]
``` ts
import { Prisma } from "@prisma/client";
import { describe, it, beforeEach, vi, expect } from "vitest";
import { SearchUsersService } from "./search-users";
import { PrismaUsersRepository } from "@/repositories/prisma/prisma-users-repository";
import PrismockClient from "prismock";
import { CreateUserService } from "./create-user";

describe("Search users service", async () => {
  let sut: SearchUsersService;
  let createUserService: CreateUserService;

  vi.mock("@prisma/client", async () => {
    const prismock: typeof PrismockClient = await vi.importActual("prismock");
    return {
      ...vi.importActual("@prisma/client"),
      PrismaClient: prismock.PrismockClient,
    };
  });

  beforeEach(() => {
    const prismaUsersRepository = new PrismaUsersRepository();
    sut = new SearchUsersService(prismaUsersRepository);
    createUserService = new CreateUserService(prismaUsersRepository);
  });

  it("should create one user", async () => {
    const user1: Prisma.UserCreateInput = {
      name: "John Doe 1",
      email: "johndoe1@email.com",
      password: "password",
    };

    await createUserService.execute(user1);
  });

  it("should be able to get all users", async () => {
    const user1: Prisma.UserCreateInput = {
      name: "John Doe 1",
      email: "johndoe1@email.com",
      password: "password",
    };

    const user2: Prisma.UserCreateInput = {
      name: "John Doe 2",
      email: "johndoe2@email.com",
      password: "password",
    };

    await createUserService.execute(user1);
    await createUserService.execute(user2);

    const { users } = await sut.execute();

    expect(users).toHaveLength(2);
    expect(users).toEqual([
      expect.objectContaining({ name: "John Doe 1" }),
      expect.objectContaining({ name: "John Doe 2" }),
    ]);
  });
});
```
![Screenshot 2023-08-27 at 17 00 53](https://github.com/morintd/prismock/assets/4152946/3a431e87-cf4b-4462-86b5-bd78dc1e1da5)

**Comment by guilherme-n** [comment]
By the way, great project man!
I was wondering if this issue is related to Vitest lib.

**Comment by morintd** [comment]
Hello @guilherme-n , thanks for the support!

I believe this issue doesn't come from Prismock itself. If you are having issue on [your repo](https://github.com/guilherme-n/healthkeeper-back), it make sense:

- You are re-instantiating a `PrismaUsersRepository` before every test, which should come with fresh data if it was instantiating a PrismaClient (mocked with Prismock).
- But every time, your `PrismaUsersRepository` use the same instance of Prisma (from `@/lib/prisma`). Even if you have different instance of `PrismaUsersRepository`, it uses the same instance and data from `prisma`.


You have two solutions here: 

- Expect an instance of `prisma` inside the constructor of `PrismaUsersRepository` so you can have control over it (dependency injection), and create a new instance of `prisma`every time in your tests
- Or, you can call the `reset`method from the prismock instance (`(prisma as PrismockClientType).reset();`) between every tests

**Comment by guilherme-n** [comment]
Yes, you are correct, I preferred to use the second approach you suggested and it worked!
By the way, I found a very concise way to mock prisma with your lib
```
import { PrismockClient } from "prismock";

vi.mock("@prisma/client", () => ({
    PrismaClient: PrismockClient,
}));
```


Still on that topic, have you ever tried to mock your lib with automated mocking like using `__mocks__`?
I created a `__mocks__/@prisma/client.ts` file and it's being called, but it seems not to mock correctly.

![Screenshot 2023-08-30 at 12 00 40](https://github.com/morintd/prismock/assets/4152946/ced89bd8-92f3-41ec-94ec-074d09b9bfd9)
-------------
![Screenshot 2023-08-30 at 12 03 16](https://github.com/morintd/prismock/assets/4152946/c2a67c05-feb5-4490-91cf-304e9ee107ce)

**Comment by morintd** [comment]
That's indeed a more elegant way to setup the mock! But with auto-mocks, you have to export the element, so it would look more like:

```
import { PrismockClient } from 'prismock';

export { PrismockClient as PrismaClient };
```

(Tested with Jest, but I guess it's the same with ViTest).
Also, you might use some other elements from the `@prisma/client` package, so I would recommend exporting everything else:

```
import { PrismockClient } from 'prismock';

export * from '@prisma/client';
export { PrismockClient as PrismaClient };
```

**Comment by guilherme-n** [comment]
It worked like a charm! thank you very much!
