### ISSUE TITLE
create: undefined field value should be assigned with the default value

### ISSUE THREAD

**Issue by lebalz** [morintd/prismock#560]
### Current behaviour

``` 
// schema.prisma
model User {
    name         String   @default("Max")
    email         String
}
```

```ts
// data is some user provided object - not guaranteed to contain both fields...
const data = { email: 'foo@bar.com' }
const { name, email } = data;
const user = await prisma.user.create({name, email}); 
// --> user.name = undefined
```

### Expected behaviour

I would expect that the default value is used, when `undefined` is used as a value. This would be the same behaviour as in in the [PrismaClient (null and undefined)](https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined).

so the correct behaviour would be

```ts
// data is some user provided object - not guaranteed to contain both fields...
const data = { email: 'foo@bar.com' }
const { name, email } = data;
const user = await prisma.user.create({name, email}); 
// --> user.name = 'Max'
```

### Where to start

I quickly looked into the code (btw. really cool project, thanks!) and i think the problem can be solved in this line:

https://github.com/morintd/prismock/blob/master/src/lib/operations/create.ts#L154

The item must be filtered first:

```diff
export function nestedCreate(current: Delegate, delegates: Delegates) {
  return (item: Item) => {
+   // remove all undefined values
+   Object.keys(item).forEach(key => item[key] === undefined && delete item[key])
    const created = { ...createDefaultValues(current.model.fields, current.getProperties()), ...item };
```

i have no time to create a pr the next two weeks - feel free to take the issue ;)

**Comment by morintd** [comment]
Thanks a lot for the support and submission @lebalz , I'm getting this fixed right now!
