### ISSUE TITLE
deprecation of setData: prismockClient.reset not working

### ISSUE THREAD

**Issue by lebalz** [morintd/prismock#562]
Since v1.19.2 `prismockClient.setData` is deprecated, and the usage of `reset()` is suggested.

When i try to use `reset()` inside `afterEach()`, consecutive tests will fail. My current work around was to use `setData` ([prismockCleaner.ts](https://github.com/lebalz/events-api/blob/main/__mocks__/prismockCleaner.ts))

```ts
afterEach(() => {
    Object.keys(prismock.getData()).forEach(key => {
        prismock.setData({[key]: []});
    });
    // prismock.reset(); /* <-- this does not work :( */
});
```

I use jest and i mock the prisma client [here](https://github.com/lebalz/events-api/blob/main/__mocks__/prismockConfig.ts) directly after the env is set (in [jest.config.js](https://github.com/lebalz/events-api/blob/main/jest.config.js) the `setupFilesAfterEnv` is used).

Is there any suggestion, how to make `reset` work? Thanks in advance 🙏

repo: https://github.com/lebalz/events-api

**Comment by morintd** [comment]
Hello @lebalz , it seems like you are keeping references to delegates (ex: `prisma.[delegate].create()`) in your code, which are overridden by the `reset` method.

I'll have a look if I can update the `reset` method to keep the high-level delegate reference, but I advise against keeping those references nonetheless.

**Comment by morintd** [comment]
Hello @lebalz , `reset` should now work for you with the latest version (1.21.0)!

**Comment by lebalz** [comment]
Hi @morintd 
Thanks a lot, it works perfect! It's a pleasure to test with prismock 👍
