### ISSUE TITLE
findUnique with compound ID

### ISSUE THREAD

**Issue by wamania** [morintd/prismock#592]
The findUnique function with compound ID doesn't seems to work
https://www.prisma.io/docs/concepts/components/prisma-client/crud#get-record-by-compound-id-or-compound-unique-identifier

Always return null

**Comment by morintd** [comment]
Hello @wamania ,

Thanks for the submission! This is indeed not implemented. I'll add it to my list but I don't expect to get it done short-term, even though I'm open to PR.
