### ISSUE TITLE
Nested create bug when creating multiple objects

### ISSUE THREAD

**Issue by artificial-aidan** [morintd/prismock#618]
When creating multiple objects using nested `create` (not `createMany`). The objects seem to fail to be created.

I wrote a test [here](https://github.com/artificialinc/prismock/commit/84b455fe2d5990462885758d03b94fb22203f44f) that captures it.

**Comment by morintd** [comment]
Helo @artificial-aidan , thanks a lot for the submission, will definitely investigate it!
