### ISSUE TITLE
nested create connect not working?

### ISSUE THREAD

**Issue by mjsilva** [morintd/prismock#624]
Hi,

Thank you so much for creating this lib!

I'm trying to integrate it on our nestjs project for e2e tests but I'm facing an issue with create & connect.

This prisma query works without prismock but with it `listingLogisticsId` is `null`. Is this not supported yet?

```typescript
const listingLogisticsPalletPrice =
  await this.prisma.listingLogisticsPalletPrice.create({
    data: {
      palletQuantity: palletQuantity,
      listingLogistics: {
        create: {
          listing: {
            connect: {
              id: listing.id,
            },
          },
          deliveryAddress: { create: quoteRequestDto.deliveryAddress },
          type: sellerCanP2p
            ? LogisticsType.P2P_SELLER
            : LogisticsType.P2P_REFRESH,
          locationName,
          buyer: { connect: { id: buyerAuthId } },
        },
      },
    },
  });
```

**Comment by morintd** [comment]
Hello @mjsilva , thanks for the submission! I believe this is a bug with Prismock, will have a look in the next few days

**Comment by morintd** [comment]
I've not been able to reproduce on my side. By any chance, @mjsilva can you provide a repo to reproduce this issue, or at the minimum your `schema.prisma` with the relation between `listingLogisticsPalletPrice`, `listingLogistics`, and `listing`?
