### ISSUE TITLE
`createMany` within `update` operation crashes

### ISSUE THREAD

**Issue by hariombalhara** [morintd/prismock#651]
It is happening because the code is expecting `createMany` to be an array itself when infact `createMany.data` is the array

![image](https://github.com/morintd/prismock/assets/1780212/4b1ce7f1-5b65-476d-a2e8-b53c958a70b7)
<img width="656" alt="Screenshot 2023-11-04 at 4 20 55 PM" src="https://github.com/morintd/prismock/assets/1780212/8325c0ad-cf89-4c28-8347-8b4d41a61024">

Btw, Thank you for this library @morintd. We have recently started using it at cal.com 🙏
I have found a few issues while using it otherwise it is exactly what we were looking for. Will slowly open PRs to fix those issues.

**Comment by morintd** [comment]
Hello @hariombalhara , thanks a lot for your submission but also cal.com for using Prismock 🙏 I'll have a look at your PR and get it merged in the next few days
