### ISSUE TITLE
Cannot be used with prisma schema parameter output / multiple clients

### ISSUE THREAD

**Issue by Valetek** [morintd/prismock#660]
As the library automatically look for the client at @prisma/client location, if we use the output parameter of prisma to move the location of the prisma client, it fail to run

Also for the same reason, we can't create multiple mock if we have multiple schema to use

Could it be possible to have a way not looking for the default client location ? or a parameter to not load it by default ?

**Comment by morintd** [comment]
Hello @Valetek ,

I'll have a look to add an option and allow using a different client location. You won't be able to use the automatic configuration with the PrismockClient class but should be able to do it manually, will let you know
