### ISSUE TITLE
Should find create a shallow copy?

### ISSUE THREAD

**Issue by atadeuccislideworks** [morintd/prismock#736]
We found an issue where we were testing an login service that should return the user object. 

Since the user object contains the password we do `delete user.password` to delete from the returning object but then the password is deleted from the in-memory database. This behavior doesn't happen when using prisma normally, since changing the object would never reflect to any database.

Should operations using find like [findOne](https://github.com/morintd/prismock/blob/master/src/lib/operations/find/find.ts#L19) do a copy of the object before returning it?

**Comment by edersonlucas** [comment]
Good issue!
