### ISSUE TITLE
Unable to Retrieve First Post Sorted in Descending Order by Field

### ISSUE THREAD

**Issue by edersonlucas** [morintd/prismock#745]
I was facing an issue while trying to find the first Post ordered by a field in descending order `desc` in my project. The problem is as follows:

Let's assume we have three `Posts`, each with a `field` named `position`. Whenever I create a `new Post`, I check what the highest existing position is and add one more (for example, if the result is `{position: 3}`, I take `3 + 1`) using the `findFirst method`, ordered by position in descending order.

**Comment by morintd** [comment]
Thanks a lot for your work @edersonlucas 🙏
