### ISSUE TITLE
Nested create does not link the nested item to the item it's nested under

### ISSUE THREAD

**Issue by codybreene** [morintd/prismock#768]
```
const shrek = await prisma.shrek.findFirst();
    await prisma.donkey.create({
      data: {
        donkey: {
          name: "david"
          connect: {
            id: shrek.id,
          },
        },
        ogre: {
          create: {
            name: "fiona",
            rawClient: {},
            agency: {
              connect: {
                id: shrek.id,
              },
            },
          },
        },
      },
    });
```

The inner `ogre` item is created, but the `ogreId` foreign key does not exist on the `donkey` object after creation. Important to note this is not an issue when using `connectOrCreate`, but in this case i'm seeding a db so the inner ogre does not exist yet, and I just want to use a nested `create`.

Using prismock version 1.26.1
Node version 18.18.1
Prisma client version 4.16.2

**Comment by morintd** [comment]
Hello @codybreene , thanks for your submission, I'll have a look and try to fix it in the next few days

**Comment by codybreene** [comment]
Thank you! I am also experiencing problems with "connectOrCreate" -- that results in an error rather than a silent failure -- let me find the blame line and add it.

Thank you for creating this! Our team very much appreciates it.

**Comment by morintd** [comment]
Thanks a lot for the support, I appreciate it 🙏

For now I added a test with this use-case, which I could confirm (in [fix/create-nested-single](https://github.com/morintd/prismock/pull/776)) and will fix it as soon as I can.
