### ISSUE TITLE
Installing package results in Checkmarx vulnerability issue

### ISSUE THREAD

**Issue by MandeeGit** [morintd/prismock#810]
Hi! Great project btw!

Attempting to add this as a dependency to our repo, and my PR is being flagged for a security vulnerability from Checkmarx vulnerability. Looks like it's coming from inflight, a dependency of MV. Open issue can be https://github.com/isaacs/inflight/issues/5.

CWE-772

![image](https://github.com/morintd/prismock/assets/161084607/f0e44241-78db-4655-b634-577a31e637a6)

**Comment by morintd** [comment]
Hello, that should have been fixed in https://github.com/morintd/prismock/commit/998f4232a9ddb770af59912762e5881e66d4721c
