### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'datamodel')

### ISSUE THREAD

**Issue by schlegz** [morintd/prismock#816]
When attempting to upgrade prisma to >= 5.9.1, I started receiving the following error in my Jest tests for a Nextjs app:

`TypeError: Cannot read properties of undefined (reading 'datamodel')`

This is occurring in any page test that has a getServerSideProps method that references database functions.  I have a monorepo that has a database package that sets up the prisma client and re-exports the @prisma/client as well as the instantiated client as follows:

```
import { PrismaClient } from '@prisma/client';
import { readReplicas } from '@prisma/extension-read-replicas';

const createExtendedClient = () => {
  const client = new PrismaClient();

  if (process.env.DATABASE_REPLICA_1_URL) {
    return client.$extends(
      readReplicas({
        url: process.env.DATABASE_REPLICA_1_URL,
      }),
    );
  }

  return client;
};

export type ExtendedPrismaClient = ReturnType<typeof createExtendedClient>;

const globalForPrisma = globalThis as unknown as {
  prisma: ExtendedPrismaClient | undefined;
};

const prisma = globalForPrisma.prisma ?? createExtendedClient();

export * from '@prisma/client';
export * from './middleware';

export { prisma };

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma;
```

**Comment by morintd** [comment]
Hello @schlegz , I’ve not been able to reproduce. By any chance, can you provide a minimal reproduction repository?

**Comment by schlegz** [comment]
@morintd Will try to put together a repo for you soon.

**Comment by schlegz** [comment]
@morintd Here is a test repo: https://github.com/schlegz/prisma-test

Run `yarn test:ci` from `apps/web` and you will see the following:

```
 FAIL  __tests__/app/page.test.tsx
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'datamodel')

      1 | import { PrismaClient } from "@prisma/client";
      2 |
    > 3 | export const prisma = global.prisma || new PrismaClient();
        |                                        ^
      4 |
      5 | if (process.env.NODE_ENV !== "production") global.prisma = prisma;
      6 |

      at Prismock.generate (../../node_modules/prismock/src/lib/client.ts:67:89)
      at new Prismock (../../node_modules/prismock/src/lib/client.ts:59:12)
      at Object.<anonymous> (../../packages/database/src/client.ts:3:40)
      at Object.<anonymous> (app/page.tsx:192:27)
      at Object.<anonymous> (__tests__/app/page.test.tsx:9:54)
```

**Comment by morintd** [comment]
Thanks a lot @schlegz , will have a look and let you know

**Comment by morintd** [comment]
Hello @schlegz , it seems like this is happening because you are in a **jsdom** environment, making `Prisma` exports their `browser` version when you try to import `@prisma/client`.

The solution is to force them to give you the `default` version. Also, **jsdom** doesn't support `structuredClone` yet, so you have to stub it:

- Install `@ungap/structured-clone`.
- Configure it:

```js
import structuredClone from "@ungap/structured-clone";

global.structuredClone = structuredClone;
```
- Replace `jest.requireActual("@prisma/client")` by `jest.requireActual("@prisma/client/default")` in `jest.setup.js`.

```js
jest.mock("@prisma/client", () => {
  return {
    ...jest.requireActual("@prisma/client/default"),
    PrismaClient: jest.requireActual("prismock").PrismockClient,
  };
});

```

**Comment by schlegz** [comment]
@morintd That fixed it!  Thanks a lot for the help, this package has been very useful.
