### ISSUE TITLE
Issues with DeleteMany

### ISSUE THREAD

**Issue by DennyBoy1989** [morintd/prismock#823]
Hello,

I might have find a bug in the deleteMany function of prismock. So, imagine this is my Prisma model:

```
model Parent {
  id          Int    @id @default(autoincrement())
  child       Child?
}

model Child {
  id          Int      @id @default(autoincrement())
  parent      Parent   @relation(fields: [parentId], references: [id], onDelete: Cascade)
  parentId    Int      @unique
}
```
There are parent objects, that have a relation to child object, but there are also some that don't.

When I try to delete all parents without children, then nothing happens. For example, I have this test function:

```
  it('Delete parents without childs', async () => {
    const prismock = new PrismockClient();

    const parent = await prismock.parent.create({
      data: {
        id: 1
      },
      include: {
        child: true
      }
    });

    const deleted = await prismock.parent.deleteMany({
      where: {
        child: {
          is: null
        }
      }
    });
    
    // I can see the parent is still in the data, even though it shouldn't be
    const data = prismock.getData();

    // One parent should be deleted
    expect(deleted).toBe(1);
  });
```
The test fails, because 0 parents are deleted. The same is happening, when I remove the "include" statement during the creation of the parent entry. I'm fairly new to Prisma, so if I've done something fundamentally wrong, I apologize :)

prismock version: 1.29.0
Prisma version: 5.9.1

Thank you very much,
Denny

**Comment by morintd** [comment]
Hello, thanks a lot for your submission, I'll have a look in the next few days
