### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'dmmf')

### ISSUE THREAD

**Issue by Farbod909** [morintd/prismock#895]
Hello there! Thank you so much for creating this library. I can't believe this isn't built-in to Prisma. Nevertheless, I'm having some issues setting this up with my simple NestJS project (which can be found [here](https://github.com/Farbod909/workout-app)).

I have a basic DatabaseModule with no dependencies that provides a DatabaseService like so:
```
@Injectable()
export class DatabaseService extends PrismaClient implements OnModuleInit {
  async onModuleInit() {
    await this.$connect();
  }
}
```
I am attempting to write some unit tests for a separate service/module that depends on this DatabaseService. Per your documentation, I created a `__mocks__` folder and followed the appropriate steps.

Then, I set up my unit test file as follows
```
import { Test, TestingModule } from '@nestjs/testing';
import { MyService } from './my.service';
import { DatabaseService } from 'src/database/database.service';

describe('MyService', () => {
  let service: MyService;
  let databaseService: DatabaseService;

  beforeEach(async () => {

    const module: TestingModule = await Test.createTestingModule({
      providers: [MyService, DatabaseService],
    }).compile();

    service = module.get<MyService>(MyService);
    databaseService = module.get<DatabaseService>(DatabaseService);
  });

  it('sample', (done) => {
    expect(service).toBeDefined();
    expect(databaseService).toBeDefined();

    databaseService.something.findMany().then((result) => {
      console.log(result);
      done();
    });
  });
});
```

This, however, results in the following error:

```
    TypeError: Cannot read properties of undefined (reading 'dmmf')

      3 |
      4 | @Injectable()
    > 5 | export class DatabaseService extends PrismaClient implements OnModuleInit {
        |        ^
      6 |   async onModuleInit() {
      7 |     await this.$connect();
      8 |   }

      at DatabaseService.generate (../node_modules/prismock/src/lib/client.ts:69:68)
      at new Prismock (../node_modules/prismock/src/lib/client.ts:59:12)
      at new DatabaseService (database/database.service.ts:5:8)
      at TestingInjector.instantiateClass (../node_modules/@nestjs/core/injector/injector.js:365:19)
      at callback (../node_modules/@nestjs/core/injector/injector.js:65:45)
      ...
```

I searched through some other issues on the repo to see if others were having similar issues and based on my findings, I tried the following 
- calling `prisma generate`
- creating a `FakeDatabaseService` and using `overrideProvider`
- using `new PrismockClient();`

What should I do to set this up properly with Nest?

**Comment by Farbod909** [comment]
Ok so the solution ended up being to mock the PrismaClient with `jest.mock` using the example provided [here](https://github.com/morintd/prismock?tab=readme-ov-file#prismaclient), instead of the "Automatic" method. 

I do wonder why the automatic method did not work though. I'm a JS novice, but it does seem to me that the "Automatic" method should work. Using some classic print-statement debugging I was able to find out that the tests are run before any logic in the `__mock__/@prisma/client.ts` is run, which is why the PrismaClient was `undefined` during the test execution (and thus causing the TypeError). But I don't have enough JS/TS know-how to figure out why.

**Comment by morintd** [comment]
Hello @Farbod909 , thanks a lot for submitting your solution. On my side, I use Prismock in a very similar context, but don't have this issue. We also had some problems related to reading the dmmf in the past, but are completely unrelated.

Your jest configure looks good to me, I'll have a look on my side but in the meantime I'll close this issue as resolved
