### ISSUE TITLE
Support for Decimal Types - DataCloneError with decimal.js

### ISSUE THREAD

**Issue by badeleux** [morintd/prismock#937]
## Description

When using prismock with entities that contain fields of type Decimal from the decimal.js library, I encounter a DataCloneError whenever I use the find method. It appears that decimal.js does not support structured cloning, which is causing this issue. Here’s the error message I receive:

```
DataCloneError: function Decimal(v) {
  var e, i, t,
    x = this;

  // Decimal called without new.
  if (!(x instanceof Decimal)) { ...<omitted>... } could not be cloned.
```

## Steps to Reproduce

	1.	Define a model that includes a Decimal field.
	2.	Use prismock to mock database operations involving this model.
	3.	Attempt to retrieve an instance of this model using the find method.

## Expected Behavior

The find method should successfully return instances of models that include Decimal types without throwing errors.

## Actual Behavior

A DataCloneError is thrown, indicating an issue with cloning Decimal types.

## Possible Solution

It would be beneficial if prismock could handle Decimal types or provide a workaround for libraries like decimal.js that do not support structured cloning.

## Additional Context

Handling of Decimal types is crucial for applications that require high precision in financial computations or other numerical calculations. Providing support or a workaround for this issue would significantly enhance prismock’s utility in such scenarios.

**Comment by badeleux** [comment]
For now, here is my workaround set-up for unit tests:

```
// Backup the original structuredClone function
const originalStructuredClone = structuredClone;

// Custom structuredClone that handles Decimal types
function customStructuredClone(input) {
    const replacer = (key, value) => {
        if (value instanceof Decimal) {
            // Convert Decimal to a serializable form
            return {type: 'Decimal', value: value.toString()};
        }
        return value;
    };

    const reviver = (key, value) => {
        if (value && value.type === 'Decimal') {
            // Convert back to Decimal
            return new Decimal(value.value);
        }
        return value;
    };

    // Use JSON stringify and parse as an example of handling custom types
    return originalStructuredClone(JSON.parse(JSON.stringify(input, replacer), reviver));
}

// Override global structuredClone with the custom function
global.structuredClone = customStructuredClone;
```

**Comment by morintd** [comment]
Hello @badeleux , thanks a lot for all the information! I'm going to have a look, will try to push a fix in the next few days

**Comment by morintd** [comment]
Hello @badeleux , I didn't find any satisfying solution without installing `Decimal.js`, which I want to avoid. Until then, I won't fix this issue directly, and will link to your workaround as showed in [use with decimal.js](https://github.com/morintd/prismock/blob/master/docs/use-with-decimal-js.md).

**Comment by leahcole** [comment]
Hi, I came across this after having the same issue and reading the documentation page on using with `Decimal.js`. I just wanted to note that this workaround does not *fully* work.

`JSON.stringify(...)` will call `Decimal.toJSON()` before running `replacer`, meaning that `if (value instanceof Decimal)` will never be true. If you do something like:
```
Decimal.prototype.toJSON = function () {
  return this;
}
```
... you'll run into the same `DataCloneError` as before. 

This *sometimes* works I think because non-zero decimal values are deserialized into numbers, but zero will be deserialized into a string.

I ran into this because I'm facing issues with [Prisma: Do not know how to serialize BigInt](https://github.com/prisma/studio/issues/614), and was hoping to tack `BigInt` onto the existing solution, rather than
```
BigInt.prototype.toJSON = function () {
  this.toString();
}
```

**Comment by leahcole** [comment]
Here's my fix for the workaround:

```
BigInt.prototype.toJSON = function () {
  return this;
};

Decimal.prototype.toJSON = function () {
  return this;
};

// Backup the original structuredClone function
const originalStructuredClone = structuredClone;

// Custom structuredClone that handles Decimal types
function customStructuredClone(input) {
  const replacer = (key, value) => {
    if (value instanceof Decimal) {
      // Convert Decimal to a serializable form
      return { type: 'Decimal', value: value.toString() };
    }
    if (typeof value === 'bigint') {
      // Convert BigInt to a serializable form
      return { type: 'BigInt', value: value.toString() };
    }
    return value;
  };

  const reviver = (key, value) => {
    if (value && value.type === 'Decimal') {
      // Convert back to Decimal
      return new Decimal(value.value);
    }
    if (value && value.type === 'BigInt') {
      // Convert back to BigInt
      return BigInt(value.value);
    }
    return value;
  };

  // Use JSON stringify and parse as an example of handling custom types
  const clone = originalStructuredClone(JSON.stringify(input, replacer));

  return JSON.parse(clone, reviver);
```
