### ISSUE TITLE
Prisma imports no longer available via autocomplete in VsCode

### ISSUE THREAD

**Issue by JoeRoddy** [morintd/prismock#941]
Love this project btw, extremely valuable for a lot of things, even outside of testing <3

One small problem I have (not a deal breaker, just annoying), when I include this dependency in my project, autocomplete suggestions stop working for Prisma, and I only get the prismock equivalent suggestion:

![image](https://github.com/morintd/prismock/assets/16690442/2266d07d-73a8-4b7f-878a-8482f6f15797)

I can hide the prismock suggestions via VsCode:
`"javascript.preferences.autoImportFileExcludePatterns": ["prismock"]`

But the prisma suggestions are still missing.  Basically what I'm doing currently is manually traveling to the top of the file and writing out the import by hand anytime I need to use Prisma, which is kind of a pain.

Unsure if this is a problem specific to my setup, or if this is a known issue?

Running a next app (14.1.4), prisma 5.12.1, prismock 1.30.2, vscode 1.89.1

tsconfig:
```json
{
  "compilerOptions": {
    "target": "es2022",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "baseUrl": "."
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "**/*.*js", "cypress/tsconfig.json"],
  "exclude": ["node_modules", "./cypress.config.ts", "cypress", "**/*.cy.ts", "scripts"]
}
```

**Comment by JoeRoddy** [comment]
Some extra context, just asked a teammate, said he's seen it in the past, but its not happening for him currently.  Currently his workspace gives him the opposite result, only Prisma suggestions and never prismock.

<img width="1036" alt="image" src="https://github.com/morintd/prismock/assets/16690442/39f80695-52d2-470b-bb9e-694fd28a246a">

**Comment by morintd** [comment]
Hello @JoeRoddy , thanks for all the information, this is indeed super annoying. I don't know where to start looking, I never had a similar problem, I'll try to think of something but I'm open to suggestions!

Thanks for the support!

**Comment by JoeRoddy** [comment]
No worries, I'm the only one on my team (out of four) this is happening to, so it's likely something to do with my environment specifically.  Thought it was worth a shot opening an issue in case you had ran into this before.

Will reply here if I figure out a fix.  Thanks for the reply!
